add_library(packet_utility STATIC)

target_sources(packet_utility PRIVATE 
    packet_in.c
    packet_out.c
)

target_link_libraries(packet_utility PUBLIC
    common
    cubemx
)

target_include_directories(packet_utility PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}
)

target_compile_options(packet_utility PUBLIC
    -std=c23
    -Wall
    -Wextra
    -Wconversion
    -Wshadow
    -Wpedantic
    -Wnarrowing
    -Waddress
    -pedantic
    -Wdeprecated
    -Wsign-conversion
    -Wduplicated-cond
    -Wduplicated-branches
    -Wlogical-op
    -Wnull-dereference
    -Wdouble-promotion
    -Wimplicit-fallthrough
    -Wcast-align
    -Wformat=2
    -Wformat-security
    -Wmissing-prototypes
    -Wmissing-declarations
    -Wstrict-prototypes
    -Wold-style-definition
    -Wundef
    -Wvla
    -Wpointer-arith
    -Wstrict-aliasing=2
)
