#ifndef DISPLAY_UTILITY_FONT5x7_H
#define DISPLAY_UTILITY_FONT5x7_H

#include <stdint.h>

#define FONT5X7_CHAR_CODE_OFFSET (32UL)
#define FONT5X7_WIDTH (5UL)
#define FONT5X7_HEIGHT (7UL)
#define FONT5X7_LINE_HEIGHT (FONT5X7_HEIGHT + 1UL)
#define FONT5X7_CHAR_WIDTH (FONT5X7_WIDTH + 1UL)
#define FONT5X7_CHARS (96UL)

extern uint8_t font5x7[FONT5X7_CHARS][5];

#endif // DISPLAY_UTILITY_FONT5x7_H