PROJECT_DIR := $(shell pwd)
MAIN_DIR := $(PROJECT_DIR)/main
BUILD_DIR := $(PROJECT_DIR)/build
CUBEMX_DIR := $(PROJECT_DIR)/cubemx
SCRIPTS_DIR := $(PROJECT_DIR)/scripts
COMPONENTS_DIR := $(PROJECT_DIR)/components
SUBMODULES_DIR := $(PROJECT_DIR)/submodules
REQUIREMENTS_DIR := $(PROJECT_DIR)/requirements

SUDO ?= sudo
PROJECT_NAME ?= project
BUILD_TYPE ?= Debug
TOOLCHAIN_FILE ?= $(CUBEMX_DIR)/cmake/gcc-arm-none-eabi.cmake
PROJECT_BINARY := $(BUILD_DIR)/main/main.elf

BASE_CMAKE_FLAGS := \
  -DCMAKE_PROJECT_NAME=$(PROJECT_NAME) \
  -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) \
  -DCMAKE_TOOLCHAIN_FILE=$(TOOLCHAIN_FILE)
EXTRA_CMAKE_FLAGS ?=
CMAKE_FLAGS := $(BASE_CMAKE_FLAGS) $(EXTRA_CMAKE_FLAGS)
