#ifndef COMMON_TERMO_NOTIFY_H
#define COMMON_TERMO_NOTIFY_H

typedef enum {
    CONTROL_NOTIFY_TEMP_READY = (1 << 0),
    CONTROL_NOTIFY_DELTA_TIMER = (1 << 1),
    CONTROL_NOTIFY_ALL =
        (CONTROL_NOTIFY_TEMP_READY | CONTROL_NOTIFY_DELTA_TIMER),
} control_notify_t;

#endif // COMMON_TERMO_NOTIFY_H